# Generated by Django 5.1.4 on 2024-12-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='x_position',
            field=models.IntegerField(default=50, help_text='X coordinate on the map (0-100)'),
        ),
        migrations.AddField(
            model_name='location',
            name='y_position',
            field=models.IntegerField(default=50, help_text='Y coordinate on the map (0-100)'),
        ),
    ]
